from enum import Enum

import streamlit as st
from langchain.output_parsers.json import SimpleJsonOutputParser
from langsmith import traceable
from langsmith.run_helpers import get_current_run_tree

logger = st.logger.get_logger("micronarratives")


class SliderOptions(Enum):
    NO = "Not really"
    EDIT = "Needs some edits"
    GOOD = "Pretty good but I'd like to tweak it"
    READY = "Ready as is!"


@traceable  # Auto-trace this function
def summariseData(
    llm_prompts,
    chat_model,
    msgs,
    extraction_chain,
    testing=False,
):
    """
    Takes the extracted answers to questions and generates three scenarios, based on
    selected prompts.

    testing (bool): will insert a dummy data instead of user-generated content if set
    to True
    """

    summary_answers = generate_summary(llm_prompts, msgs, extraction_chain, testing)
    generate_scenarios_with_progress(llm_prompts, chat_model, summary_answers)


def generate_summary(llm_prompts, msgs, extraction_chain, testing):
    """
    Generate a dictionary containing a summary of the key points of the conversation.
    The LLM-generated dictionary is not guaranteed to contain the keys specified in the
    configuration file, so this function pulls out the required keys and leaves them
    blank if a corresponding key-value pair was not generated by the LLM as a result of
    the conversation.
    """

    if testing:
        logger.info("Using testing messages")
        message_history = llm_prompts.one_shot_conversation
    else:
        message_history = msgs
    answer_set = extraction_chain.invoke({"conversation_history": message_history})

    summary_answers = {key: answer_set.get(key, "") for key in llm_prompts.summary_keys}
    st.session_state["summary_answers"] = summary_answers

    return summary_answers


def generate_scenarios(llm_prompts, chat_model, summary_answers, bar):
    """
    Generates the scenarios from the user's summary answers, in the style of each of the
    personas. As scenarios are generated, updates the progress bar.
    """

    # Create the chain for generating a scenario based on the conversation
    scenario_chain = (
        llm_prompts.scenario_prompt_template | chat_model | SimpleJsonOutputParser()
    )

    scenarios = []

    for count, persona in enumerate(llm_prompts.personas):
        scenarios.append(
            scenario_chain.invoke({"persona": persona} | summary_answers)[
                "output_scenario"
            ]
        )
        bar.progress(
            (count + 1) / len(llm_prompts.personas),
            f"Processed scenario {count + 1} of {len(llm_prompts.personas)}",
        )

    return scenarios


def generate_scenarios_with_progress(llm_prompts, chat_model, summary_answers):
    """
    Sets up the streamlit page for scenario generation.
    """

    st.markdown("#### Summarising your story")
    messages_container = st.container(border=True)

    with messages_container:
        st.chat_message("ai").write(
            "Seems I have everything! "
            "Let me try to summarise what you said in three scenarios. \n"
            "See you if you like any of these! "
        )
        progress_text = "Processing your scenarios"
        bar = st.progress(0, text=progress_text)

        scenarios = generate_scenarios(llm_prompts, chat_model, summary_answers, bar)
        st.session_state["generated_scenarios"] = scenarios

    # Store the run ID to re-use when handling feedback (all here are the same)
    st.session_state["langsmith_run_id"] = get_current_run_tree().id

    # Update state and manually trigger a page refresh via button press
    # (Note that refreshing via e.g. st.rerun() can give 'failed runs' on LangSmith)
    st.session_state["agentState"] = "review"
    st.button("I'm ready -- show me!", key="progressButton")


def click_selection_yes(index):
    """
    Function called on_submit when a final scenario is selected.

    Saves the index of the selected scenario into Streamlit's session state.
    Args:
        index: the index of the scenario preferred by the user
    """
    st.session_state["selected_scenario_index"] = index


def click_selection_no(index):
    """
    Function called on_submit when a user decides to try another scenario. Resets the
    judgement record to prevent the user from proceeding further with this scenario
    without further input.

    Args:
        index (int): index of the scenario to which the button corresponds
    """

    st.session_state["scenario_judgement"][index] = ""


def sliderChange(slider_name, index):
    """
    Updates the scenario judgement record when the corresponding slider is changed.

    Args:
        slider_name (str): name of the slider
        index (int): index of the scenario to which the slider corresponds
    """

    st.session_state["scenario_judgement"][index] = st.session_state[slider_name]


def scenario_selection(popover, index):
    """
    Helper function which sets up the text & infrastructure for each scenario popover.

    Arguments:
    popover: streamlit popover object that we are operating on
    button_num (str): allows us to keep track which scenario col the popover belongs to
    scenario (str): the text of the scenario that the button refers to
    """
    with popover:
        st.markdown(f"How well does Scenario {index + 1} capture what you had in mind?")
        slider_name = f"slider_scenario_{index}"

        st.select_slider(
            "Judge_scenario",
            label_visibility="hidden",
            key=slider_name,
            options=[opt.value for opt in SliderOptions],
            on_change=sliderChange,
            args=(slider_name, index),
        )

        c1, c2 = st.columns(2)

        # A judgement must be provided before the user can accept the scenario
        c1.button(
            "Continue with this scenario 🎉",
            key=f"yeskey_{index}",
            on_click=click_selection_yes,
            args=(index,),
            disabled=not st.session_state["scenario_judgement"][index],
        )

        # The user can always switch to a different scenario; doing so resets any
        # judgement they have given via the slider
        c2.button(
            "Actually, let me try another one 🤨",
            key=f"nokey_{index}",
            on_click=click_selection_no,
            args=(index,),
        )


def finaliseScenario(chat_model, adaptation_prompt_template):
    """
    Prepares the final version of the scenario selected by the user. If they were happy
    with the text as originally generated, this function skips immediately to the next
    stage (saving the data and concluding the interaction with the user). Otherwise, the
    user is invited to propose modifications and iterate on them first.

    Args:
        chat_model (ChatOpenAI): OpenAI chat model
        adaptation_prompt_template (LangChain.PromptTemplate): instructions for the bot
            to adapt the proposed scenario according to suggestions by the user
    """

    # If not already done, initialise a copy of the selected scenario for adaptation
    if not st.session_state["final_scenario"]:
        st.session_state["final_scenario"] = st.session_state["generated_scenarios"][
            st.session_state["selected_scenario_index"]
        ]

    if (
        st.session_state["scenario_judgement"][
            st.session_state["selected_scenario_index"]
        ]
        == SliderOptions.READY.value
    ):
        st.session_state["agentState"] = "save"
        st.rerun()
    else:
        display_adaptation_page(chat_model, adaptation_prompt_template)


def display_adaptation_page(chat_model, adaptation_prompt_template):
    """
    Generates a page where the user can propose an adaptation to their scenario and give
    feedback on the updated scenario.

    Args:
        chat_model (ChatOpenAI): OpenAI chat model
        adaptation_prompt_template (LangChain.PromptTemplate): instructions for the bot
            to adapt the proposed scenario according to suggestions by the user
    """

    st.markdown("#### Adapt your scenarios")
    container = st.container(border=True)
    chat_input = st.chat_input()

    with container:
        st.markdown(
            "It seems that you selected a scenario that you liked:\n\n"
            f":green[{st.session_state['final_scenario']}]"
        )
        st.markdown(
            "... but that you also think it: "
            f":red[{st.session_state['scenario_judgement'][st.session_state['selected_scenario_index']]}]"
        )

        st.chat_message("ai").write(
            "Okay, what's missing or could change to make this better?"
        )

    if chat_input:
        with container:
            st.chat_message("human").write(chat_input)

        updated_scenario = update_scenario_with_progress(
            container, chat_model, adaptation_prompt_template, chat_input
        )

        get_feedback(container, updated_scenario)


def update_scenario_with_progress(
    container, chat_model, adaptation_prompt_template, chat_input
):
    """
    Shows a progress spinner as the scenario is adapted by the chat model.

    Args:
        container (st.container): Streamlit container where the spinner should be shown
        chat_model (ChatOpenAI): OpenAI chat model
        adaptation_prompt_template (LangChain.PromptTemplate): instructions for the bot
            to adapt the proposed scenario according to suggestions by the user
        chat_input (str): the user-provided suggestion to improve the scenario

    Returns:
        str: text of the revised scenario
    """

    with container, st.spinner("Working on your updated scenario 🧐"):
        updated_scenario = update_scenario(
            chat_model, adaptation_prompt_template, chat_input
        )
    return updated_scenario


def get_feedback(container, updated_scenario):
    """
    Requests feedback on the updated scenario. If the user is happy, the next state of
    the app is triggered to save the data and conclude. Otherwise, the user can either
    continue with adaptations from the current scenario text, or reset to the original
    text and adapt again from there.

    Args:
        container (st.container): Streamlit container where the text should be shown
        updated_scenario (str): text of the revised scenario
    """

    with container:
        st.markdown(
            f"Here is the adaptation of the scenario above:\n\n"
            f":orange[{updated_scenario}]\n\n **What do you think?**"
        )

        c1, c2, c3 = st.columns(3)

        c1.button(
            "All good!",
            icon="🎉",
            use_container_width=True,
            on_click=confirmFinalScenario,
            args=(updated_scenario,),
        )

        c2.button(
            "Adapt further",
            icon="💬",
            use_container_width=True,
            on_click=iterateFinalScenario,
            args=(updated_scenario,),
        )

        c3.button(
            "Reset to original",
            icon="↩️",
            use_container_width=True,
            on_click=resetFinalScenario,
        )


@traceable
def update_scenario(chat_model, adaptation_prompt_template, chat_input):
    """
    Use the chat model to apply an update to the scenario as suggested by the user.

    Args:
        chat_model (ChatOpenAI): OpenAI chat model
        adaptation_prompt_template (LangChain.PromptTemplate): instructions for the bot
            to adapt the proposed scenario according to suggestions by the user
        chat_input (str): the user-provided suggestion to improve the scenario

    Returns:
        str: text of the updated scenario
    """

    json_parser = SimpleJsonOutputParser()
    chain = adaptation_prompt_template | chat_model | json_parser
    new_response = chain.invoke(
        {
            "scenario": st.session_state["final_scenario"],
            "input": chat_input,
        }
    )

    return new_response["new_scenario"]


def resetFinalScenario():
    """
    Sets the final version of the scenario to match that originally generated by the
    selected persona, discarding any further changes.
    """

    st.session_state["final_scenario"] = st.session_state["generated_scenarios"][
        st.session_state["selected_scenario_index"]
    ]


def iterateFinalScenario(new_scenario):
    """
    Updates the scenario text in the session state, in preparation for a further round
    of edits.

    Args:
        new_scenario (str): text of the updated version of the scenario
    """

    st.session_state["final_scenario"] = new_scenario


def confirmFinalScenario(new_scenario):
    """
    Records the final scenario text in the session state, and switches the state of the
    app to "save", where the data will be stored.

    Args:
        new_scenario (str): text of the final version of the scenario, potentially
        containing amendments from the user
    """

    st.session_state["final_scenario"] = new_scenario
    st.session_state["agentState"] = "save"
